---
# Optional method of pinning a specific version of Jenkins and/or overriding the
# default Jenkins packaging URL.
# jenkins_pkg_url: "https://www.example.com/"

jenkins_repo_key_url: "http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key"
jenkins_repo_url: "deb http://pkg.jenkins-ci.org/debian binary/"
jenkins_pkg_url: "https://pkg.jenkins.io/debian-stable/binary/"
jenkins_version: "1.651.3"
# jenkins_version: "2.89.2" # Force install of 2.89.2 stable
jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: /var/lib/jenkins
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_plugins: []
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

jenkins_admin_username: admin
jenkins_admin_password: dojoadmin
jenkins_admin_password_file: ""

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "JENKINS_JAVA_OPTIONS"
    value: "{{ jenkins_java_options }}"
