---
- apt: pkg={{item}} state=present force=yes cache_valid_time=3600
  with_items:
    - nagios3
    - nagios-nrpe-plugin
    - dc

- sudo: yes
  copy: src={{item}} dest=/etc/nagios3/conf.d/{{item}} force=yes mode=0644
  with_items:
      - app-server-node-1.cfg
      - app-server-node-2.cfg
      - app-server-node-3.cfg
      - app-server-node-4.cfg
      - checkmem.cfg
      - ci-node.cfg
      - ci-repo.cfg
      - monitoring-node.cfg
      - mongodb-node.cfg
      - localhost_nagios2.cfg
      - services_nagios2.cfg
      - extinfo_nagios2.cfg
      - hostgroups_nagios2.cfg

- get_url: url='http://exchange.nagios.org/components/com_mtree/attachment.php?link_id=3329&cf_id=24' dest=/usr/lib/nagios/plugins/check_mem owner=root mode=0744

- sudo: yes
  copy: src=nagios.cfg dest=/etc/nagios3/nagios.cfg force=yes mode=0644

- sudo: yes
  copy: src=disk.cfg dest=/etc/nagios-plugins/config/disk.cfg force=yes mode=0644

- sudo: yes
  file: path=/var/log/nagios state=directory

- sudo: yes
  copy: src=htpasswd.users dest=/etc/nagios3/htpasswd.users force=yes mode=0644
  notify: restart nagios3
