---
- name: Add dojo user account
  user:
    name: "{{item}}"
    comment: "Dojo jumpstation account"
  with_items:
    - dojo1
    - dojo2

- name: "Create jumpstation ssh key to all other servers"
  command: ssh-keygen -t rsa -b 2048 -f .ssh/id_rsa -q -N ""
  args:
    creates: .ssh/id_rsa

- name: Getting private key
  command: cat .ssh/id_rsa
  register: id_rsa

- name: create local dojo users .ssh directory
  sudo: true
  sudo_user: "{{ item }}"
  file:
    path: /home/{{item}}/.ssh
    mode: 0755
    state: directory
  with_items:
    - dojo1
    - dojo2

- name: Put private key on all dojo users
  sudo: yes
  sudo_user: "{{ item }}"
  lineinfile:
    dest: /home/{{item}}/.ssh/id_rsa
    line: "{{ id_rsa.stdout }}"
    owner: "{{item}}"
    mode: 0600
    create: yes
    state: present
  with_items:
    - dojo1
    - dojo2

- name: Getting public key
  command: cat .ssh/id_rsa.pub
  register: id_rsa_pub

- name: "Add pub key to authorized_keys"
  authorized_key:
    user: "hos"
    state: present
    key: "{{ id_rsa_pub.stdout }}"
  delegate_to: "{{ item }}"
  with_inventory_hostnames: all

- name: install vnc and applications environment
  apt: pkg={{item}} state=present force=yes
  with_items:
    - xfce4
    - firefox
    - chromium-browser
    - xfce4-goodies
    - tightvncserver
    - xfonts-base
    - chromium-browser

- name: install vnc configuration
  sudo: yes
  sudo_user: "{{item}}"
  copy: src=.Xauthority dest=/home/{{item}}/.Xauthority force=yes mode=700 owner={{item}}
  with_items:
    - dojo1
    - dojo2

- sudo: yes
  sudo_user: "{{item}}"
  file:
    path: "/home/{{item}}/.vnc"
    state: directory
    owner: "{{item}}"
    mode: 0755
  with_items:
    - dojo1
    - dojo2

- name: set vnc password
  sudo: yes
  sudo_user: "{{item}}"
  shell: echo d0j04fun | vncpasswd -f > passwd && chmod 600 passwd
  args:
    creates: /home/{{item}}/.vnc/passwd
    chdir: /home/{{item}}/.vnc/
  with_items:
    - dojo1
    - dojo2

- name: install vnc configuration
  copy: src=xstartup dest=/home/{{item}}/.vnc/xstartup force=yes mode=700 owner={{item}}
  with_items:
    - dojo1
    - dojo2

- name: install vnc init script
  template:
    src: vncserver@.service
    dest: /etc/systemd/system/vncserver-{{item}}@.service
    mode: 0644
    owner: root
  notify:
    - restart vnc
  with_items:
    - dojo1
    - dojo2

- name: Start VNC
  systemd:
    state: started
    enabled: yes
    name: vncserver-{{item.user}}@{{item.display}}
  with_items:
    - user: dojo1
      display: 1
    - user: dojo2
      display: 2


